### PR TITLE
User Edit Feature

### PR DESCRIPTION
**Pull request by Jengwen**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Related Ticket(s)
16

## Steps to Test
From the bangazon-site-dog-2-0 file , you checkout to branch jj-userEdit. Open the solution and enter Visual Studio. When you start the solution you will be able to push the green arrow IIS Express you will open the web application.
Log in with a user and click on that user's email address in the top right.
You will see a user profile, with first Name, Last Name, phone number and address
You can not edit first name, but you can edit last  name, address, and phone number.
Try changing the last name or address and click save.
This should bring you back an edited profile with the new information.

# Checklist:
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new errors

### CODE REVIEW

**Comment by DarylAdkins** [comment]
I was able to change information in the correct fields, but the changed information was not saved.

**Comment by Jengwen** [comment]
Fields are now all saving

**Comment by JacobPerry34** [comment]
I was able to change the User Info mentioned and it saved accordingly.

**Comment by DarylAdkins** [comment]
I was able to change info in last name, address and phone. All changes were saved and then I was redirected to the details page

**Pull request merged**
